name: Metrics
on:
  # Schedule updates (every 24 hours)
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Allow manual dispatch
  workflow_dispatch:
  # (optional) Run on push to main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General User Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: giuraionut
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Europe/Bucharest
          
          # Plugin: Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          # Plugin: Habits (Coding hours/activity)
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_days: 14
          
          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact
          
          # Output configuration
          filename: github-metrics.svg
          optimize: svg
